-- Kira — bootstrap a NEW Supabase project.
--
-- GENERATED by scripts/bundle-migrations.mjs. Do not hand-edit: edit the
-- migrations in supabase/migrations/ and re-run it. A test fails if this file
-- and those migrations disagree.
--
-- WHAT THIS IS
--   All 9 migrations concatenated in order, so a fresh project reaches the
--   current schema in ONE paste. It is for an EMPTY project only.
--
-- DO NOT RUN THIS AGAINST PRODUCTION (ccbioktxfpeqaocjkqpr).
--   Production already has 0001-0009 applied. Re-running would not be a
--   harmless no-op: 0001 creates tables, and `create table` without
--   `if not exists` errors rather than skipping. Some statements would abort
--   and others would not, which is the half-applied state that is genuinely
--   hard to reason about afterwards.
--
-- WHY ONE BLOCK
--   0006 was once handed over split across two messages and only the first
--   half ran — column and CHECK created, three functions missing. It looked
--   exactly like a stale PostgREST schema cache. Diagnose that class of
--   problem with `select proname from pg_proc where pronamespace =
--   'public'::regnamespace` BEFORE reaching for a schema reload.
--
-- AFTER PASTING
--   Check the function list is complete, then point a client at the new
--   project and confirm RLS actually denies a cross-user read. A table created
--   without `enable row level security` looks like a working feature from the
--   client and is a wide-open door.
--
-- Files, in application order:
--   0001_init.sql
--   0002_classes.sql
--   0003_leaderboard.sql
--   0004_push_reminders.sql
--   0005_roster_rollup.sql
--   0006_avatars.sql
--   0007_last_wrong_answer.sql
--   0008_item_notes.sql
--   0009_class_insight.sql

-- ===========================================================================
-- 0001_init.sql
-- ===========================================================================

-- Kira — initial schema (Build Spec §5)
-- Paste this into the Supabase SQL Editor and run it.
-- Safe to re-run: every statement is idempotent.

-- ---------------------------------------------------------------------------
-- profiles: one row per learner
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id           uuid primary key references auth.users on delete cascade,
  display_name text,
  locale       text not null default 'ms' check (locale in ('ms', 'en')),
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- review_state: Leitner state, one row per (user, item)
-- ---------------------------------------------------------------------------
create table if not exists public.review_state (
  user_id     uuid not null references auth.users on delete cascade,
  item_id     text not null,
  box         int  not null default 1 check (box between 1 and 5),
  due_at      timestamptz not null,
  streak      int  not null default 0,
  last_result boolean,
  updated_at  timestamptz not null default now(),
  primary key (user_id, item_id)
);

-- session queue reads "my rows that are due"
create index if not exists review_state_user_due_idx
  on public.review_state (user_id, due_at);

-- ---------------------------------------------------------------------------
-- attempts: every answer, for analytics + mastery
-- ---------------------------------------------------------------------------
create table if not exists public.attempts (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users on delete cascade,
  item_id    text not null,
  correct    boolean not null,
  chosen     jsonb,
  ms_taken   int,
  created_at timestamptz not null default now()
);

create index if not exists attempts_user_created_idx
  on public.attempts (user_id, created_at desc);

-- the sync queue may retry a flush; make replays idempotent
create unique index if not exists attempts_user_item_created_uniq
  on public.attempts (user_id, item_id, created_at);

-- ---------------------------------------------------------------------------
-- Row Level Security — a user may only touch their own rows.
-- This is the ONLY boundary: Kira ships a publishable key in a public bundle.
-- ---------------------------------------------------------------------------
alter table public.profiles     enable row level security;
alter table public.review_state enable row level security;
alter table public.attempts     enable row level security;

drop policy if exists "profiles are self-service" on public.profiles;
create policy "profiles are self-service" on public.profiles
  for all
  using      (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "review_state is self-service" on public.review_state;
create policy "review_state is self-service" on public.review_state
  for all
  using      (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "attempts are self-service" on public.attempts;
create policy "attempts are self-service" on public.attempts
  for all
  using      (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Create a profile automatically on sign-up (including anonymous sign-in).
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===========================================================================
-- 0002_classes.sql
-- ===========================================================================

-- Kira — classroom / teacher model (Build Spec §4 extension)
-- Paste this into the Supabase SQL Editor and run it, AFTER 0001_init.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Model
--   A teacher is any user who owns a `classes` row. Learners join a class with
--   a short code (via the join_class RPC). A teacher may READ — never write —
--   the review_state / attempts / profile of learners in their own classes.
--
-- The single most important security property: a teacher can ONLY read a
-- learner who has themselves joined one of the teacher's classes. There is no
-- path for a teacher to add an arbitrary user to a class, so a teacher can
-- never gain read access to someone who never opted in. Enforced by:
--   * the only INSERT into class_members is join_class(), which inserts
--     auth.uid() (the caller) and nobody else, and
--   * class_members has NO direct INSERT/UPDATE policy (default-deny), so
--     PostgREST cannot be used to forge a membership.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists public.classes (
  id         uuid primary key default gen_random_uuid(),
  owner_id   uuid not null references auth.users on delete cascade,
  name       text not null,
  join_code  text not null unique,
  revoked    boolean not null default false,
  created_at timestamptz not null default now()
);

-- (added after review) allow re-running over an earlier install of this file
alter table public.classes
  add column if not exists revoked boolean not null default false;

create index if not exists classes_owner_idx on public.classes (owner_id);

create table if not exists public.class_members (
  class_id  uuid not null references public.classes on delete cascade,
  user_id   uuid not null references auth.users   on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (class_id, user_id)
);

-- "which classes is this learner in" and "who is in this class"
create index if not exists class_members_user_idx  on public.class_members (user_id);
create index if not exists class_members_class_idx on public.class_members (class_id);

-- ---------------------------------------------------------------------------
-- SECURITY DEFINER helpers.
-- RLS policies that cross-reference classes <-> class_members would recurse
-- (each table's policy querying the other). These helpers run with the
-- definer's rights, so the lookups inside them DO NOT re-trigger RLS, breaking
-- the cycle. They are STABLE and read-only.
-- ---------------------------------------------------------------------------

-- Does the current user OWN the given class?
create or replace function public.owns_class(cls uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.classes c
    where c.id = cls and c.owner_id = auth.uid()
  );
$$;

-- Is the current user a MEMBER of the given class?
create or replace function public.is_member_of(cls uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.class_members m
    where m.class_id = cls and m.user_id = auth.uid()
  );
$$;

-- Is the current user the teacher of SOME class that `member` belongs to?
-- This is the gate for a teacher reading a learner's progress.
create or replace function public.is_teacher_of(member uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.class_members m
    join public.classes c on c.id = m.class_id
    where m.user_id = member
      and c.owner_id = auth.uid()
  );
$$;

-- ---------------------------------------------------------------------------
-- RPCs. Membership is only ever created through these, never by direct writes.
-- ---------------------------------------------------------------------------

-- Create a class owned by the caller, generating a unique join code.
--
-- The code is 12 hex chars (48 bits, ~2.8e14). A 6-char code was only 24 bits
-- — enumerable in hours against join_class, which would let an attacker sweep
-- the space, self-enrol into arbitrary classes and read their metadata. Entropy
-- is what closes that; the UI formats the code in groups so it stays typeable.
create or replace function public.create_class(p_name text)
returns public.classes
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_row  public.classes;
begin
  if auth.uid() is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  -- Cap classes per owner: create_class is reachable by any throwaway
  -- anonymous session, so without this the table can be spammed without bound.
  if (select count(*) from public.classes where owner_id = auth.uid()) >= 50 then
    raise exception 'class limit reached' using errcode = '53400';
  end if;

  -- retry on the (astronomically unlikely) code collision
  loop
    v_code := upper(substr(md5(gen_random_uuid()::text), 1, 12));
    begin
      insert into public.classes (owner_id, name, join_code)
      values (auth.uid(), coalesce(nullif(btrim(p_name), ''), 'My Class'), v_code)
      returning * into v_row;
      return v_row;
    exception when unique_violation then
      -- code already taken; loop and try another
    end;
  end loop;
end;
$$;

-- Join the class with the given code. Inserts the CALLER as a member; there is
-- deliberately no way to enrol anyone else. Returns the class id.
create or replace function public.join_class(p_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_class_id uuid;
begin
  if auth.uid() is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  -- accept a code typed with spaces or dashes (the UI shows it grouped)
  select id into v_class_id
  from public.classes
  where join_code = upper(translate(btrim(p_code), ' -', ''))
    and not revoked;

  if v_class_id is null then
    raise exception 'invalid join code' using errcode = 'no_data_found';
  end if;

  insert into public.class_members (class_id, user_id)
  values (v_class_id, auth.uid())
  on conflict (class_id, user_id) do nothing;

  return v_class_id;
end;
$$;

-- Issue a fresh join code for a class the caller owns, so a leaked or
-- over-shared code can be retired without losing the existing roster.
create or replace function public.rotate_join_code(p_class_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
begin
  if not public.owns_class(p_class_id) then
    raise exception 'not the owner of this class' using errcode = '42501';
  end if;

  loop
    v_code := upper(substr(md5(gen_random_uuid()::text), 1, 12));
    begin
      update public.classes
        set join_code = v_code, revoked = false
        where id = p_class_id;
      return v_code;
    exception when unique_violation then
      -- code already taken; loop and try another
    end;
  end loop;
end;
$$;

revoke all on function public.create_class(text)     from public;
revoke all on function public.join_class(text)       from public;
revoke all on function public.rotate_join_code(uuid) from public;
grant execute on function public.create_class(text)     to anon, authenticated;
grant execute on function public.join_class(text)       to anon, authenticated;
grant execute on function public.rotate_join_code(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.classes       enable row level security;
alter table public.class_members enable row level security;

-- classes: a teacher fully manages their own; members may read (to see the
-- class name they belong to). No membership INSERT path lives here.
drop policy if exists "read own or joined classes" on public.classes;
create policy "read own or joined classes" on public.classes
  for select
  using (owner_id = auth.uid() or public.is_member_of(id));

drop policy if exists "teacher inserts own class" on public.classes;
create policy "teacher inserts own class" on public.classes
  for insert
  with check (owner_id = auth.uid());

drop policy if exists "teacher updates own class" on public.classes;
create policy "teacher updates own class" on public.classes
  for update
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists "teacher deletes own class" on public.classes;
create policy "teacher deletes own class" on public.classes
  for delete
  using (owner_id = auth.uid());

-- class_members: readable by the member themselves and by the class's teacher.
-- A member may remove themselves; a teacher may remove anyone from their class.
-- There is NO insert/update policy: joining goes through join_class() only.
drop policy if exists "read own or taught memberships" on public.class_members;
create policy "read own or taught memberships" on public.class_members
  for select
  using (user_id = auth.uid() or public.owns_class(class_id));

drop policy if exists "leave or be removed" on public.class_members;
create policy "leave or be removed" on public.class_members
  for delete
  using (user_id = auth.uid() or public.owns_class(class_id));

-- ---------------------------------------------------------------------------
-- Teacher READ access to learner data. These are additive SELECT-only policies
-- alongside the existing self-service policies from 0001, so a teacher can see
-- a member's rows but the write policies (still auth.uid() = user_id) mean a
-- teacher can never modify them.
-- ---------------------------------------------------------------------------
drop policy if exists "teachers read members' review_state" on public.review_state;
create policy "teachers read members' review_state" on public.review_state
  for select
  using (public.is_teacher_of(user_id));

drop policy if exists "teachers read members' attempts" on public.attempts;
create policy "teachers read members' attempts" on public.attempts
  for select
  using (public.is_teacher_of(user_id));

drop policy if exists "teachers read members' profiles" on public.profiles;
create policy "teachers read members' profiles" on public.profiles
  for select
  using (public.is_teacher_of(id));

-- ===========================================================================
-- 0003_leaderboard.sql
-- ===========================================================================

-- Kira — class leaderboard (gamification)
-- Paste into the Supabase SQL Editor and run, AFTER 0002_classes.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Why a function instead of new RLS policies
--   A leaderboard needs classmates to see each other, but 0002 deliberately
--   keeps learners blind to one another — a member is not a teacher, and
--   review_state / attempts stay private. Loosening those policies to enable a
--   leaderboard would expose every raw answer to every classmate.
--
--   This SECURITY DEFINER function is the narrow alternative: it returns ONLY
--   (rank, display name, score) for a class the caller actually belongs to.
--   The underlying tables stay locked down; no policy is weakened.
--
-- The metric: distinct items practised in the window. It is self-capping —
-- there are only so many items, and hammering one repeatedly counts once — so
-- it rewards steady review rather than grinding. Ranking by raw XP would
-- reward volume and pull learners away from their due reviews, which is the
-- behaviour spaced repetition exists to produce.

create or replace function public.class_leaderboard(
  p_class_id uuid,
  p_since    timestamptz
)
returns table (
  user_id      uuid,
  display_name text,
  score        bigint
)
language plpgsql
security definer
stable
set search_path = public
as $$
begin
  -- The caller must be IN the class or OWN it. Without this guard a definer
  -- function would happily leak any class's roster to anyone who knows an id.
  if not (public.is_member_of(p_class_id) or public.owns_class(p_class_id)) then
    raise exception 'not a member of this class' using errcode = '42501';
  end if;

  return query
    select
      m.user_id,
      coalesce(nullif(btrim(p.display_name), ''), 'Learner') as display_name,
      count(distinct a.item_id) as score
    from public.class_members m
    left join public.profiles p
      on p.id = m.user_id
    left join public.attempts a
      on a.user_id = m.user_id
     and a.created_at >= p_since
    where m.class_id = p_class_id
    group by m.user_id, p.display_name
    -- every member appears, including those who have practised nothing yet
    order by count(distinct a.item_id) desc, display_name asc;
end;
$$;

revoke all on function public.class_leaderboard(uuid, timestamptz) from public;
grant execute on function public.class_leaderboard(uuid, timestamptz)
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Let a learner set their own display name, so the leaderboard is readable.
-- profiles already has a self-service policy from 0001; this just makes the
-- intent explicit and keeps the column trimmed to something sane.
-- ---------------------------------------------------------------------------
create or replace function public.set_display_name(p_name text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clean text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;
  v_clean := nullif(btrim(left(p_name, 24)), '');
  update public.profiles set display_name = v_clean where id = auth.uid();
  return v_clean;
end;
$$;

revoke all on function public.set_display_name(text) from public;
grant execute on function public.set_display_name(text) to anon, authenticated;

-- ===========================================================================
-- 0004_push_reminders.sql
-- ===========================================================================

-- Kira — web push daily reminders
-- Paste into the Supabase SQL Editor and run, AFTER 0003_leaderboard.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Why reminders matter here: spaced repetition only works if the learner comes
-- back on the day an item is due. The reminder is the delivery mechanism, not
-- decoration — a review nobody returns for simply does not happen.

-- ---------------------------------------------------------------------------
-- One row per browser/device push subscription. A learner may have several
-- (phone, laptop), so the endpoint is the natural key.
-- ---------------------------------------------------------------------------
create table if not exists public.push_subscriptions (
  endpoint    text primary key,
  user_id     uuid not null references auth.users on delete cascade,
  p256dh      text not null,
  auth        text not null,
  -- IANA zone name, e.g. 'Asia/Kuala_Lumpur'. Stored per subscription because
  -- the same learner's laptop and phone can be in different places.
  timezone    text not null default 'UTC',
  /* local hour (0-23) the learner wants to be nudged */
  send_hour   int  not null default 19 check (send_hour between 0 and 23),
  /* set after each send so the cron cannot nag twice in a day */
  last_sent_on date,
  failure_count int not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;

-- Self-service only. Notably NOT readable by a teacher: a push endpoint is a
-- device handle, not progress, and nothing in the teacher dashboard needs it.
drop policy if exists "push subs are self-service" on public.push_subscriptions;
create policy "push subs are self-service" on public.push_subscriptions
  for all
  using      (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Who should be nudged right now?
--
-- SECURITY DEFINER because the sender runs as the service role and needs to
-- read across users. Returns only what a push needs: where to send, how to
-- encrypt, and how many reviews are waiting. No answers, no progress detail.
--
-- Selection rules, in order of how easily each gets forgotten:
--   * the learner's LOCAL hour must equal their chosen hour
--   * they must not already have been sent one today (their local date)
--   * they must actually have reviews due — never send "you have 0 reviews"
--   * dead endpoints (5+ consecutive failures) are skipped
-- ---------------------------------------------------------------------------
create or replace function public.due_reminders()
returns table (
  endpoint  text,
  p256dh    text,
  auth      text,
  due_count bigint,
  local_date date
)
language sql
security definer
stable
set search_path = public
as $$
  select
    s.endpoint,
    s.p256dh,
    s.auth,
    count(r.item_id) as due_count,
    (now() at time zone s.timezone)::date as local_date
  from public.push_subscriptions s
  join public.review_state r
    on r.user_id = s.user_id
   and r.due_at <= now()
  where s.failure_count < 5
    and extract(hour from (now() at time zone s.timezone))::int = s.send_hour
    and (s.last_sent_on is null
         or s.last_sent_on < (now() at time zone s.timezone)::date)
  group by s.endpoint, s.p256dh, s.auth, s.timezone
  having count(r.item_id) > 0;
$$;

revoke all on function public.due_reminders() from public, anon, authenticated;
-- service_role only: this is the sender's query, never the client's.
grant execute on function public.due_reminders() to service_role;

-- Bookkeeping for the sender: mark a send, or record a failure so a dead
-- endpoint eventually stops being retried forever.
create or replace function public.mark_reminder_sent(
  p_endpoint text,
  p_date     date
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.push_subscriptions
     set last_sent_on = p_date, failure_count = 0
   where endpoint = p_endpoint;
$$;

create or replace function public.mark_reminder_failed(p_endpoint text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.push_subscriptions
     set failure_count = failure_count + 1
   where endpoint = p_endpoint;
$$;

revoke all on function public.mark_reminder_sent(text, date) from public, anon, authenticated;
revoke all on function public.mark_reminder_failed(text)     from public, anon, authenticated;
grant execute on function public.mark_reminder_sent(text, date) to service_role;
grant execute on function public.mark_reminder_failed(text)     to service_role;

-- ===========================================================================
-- 0005_roster_rollup.sql
-- ===========================================================================

-- Kira — server-side roster roll-up (teacher / parent progress tracking)
-- Paste into the Supabase SQL Editor and run, AFTER 0004_push_reminders.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Why this exists
--   The roster used to be built client-side: fetch EVERY review_state row and
--   EVERY attempt row for every member, then roll them up in JS. That is wrong
--   in a way that gets worse the more the app is used — PostgREST caps a
--   response at the project's "Max rows" setting (Supabase default 1000) and
--   TRUNCATES SILENTLY. With 186 items, half a dozen active learners exceeds
--   that on review_state alone, and one busy learner exceeds it on attempts
--   within weeks. Nothing errors; the teacher just starts seeing mastery,
--   accuracy and weak-skill numbers computed from an arbitrary slice.
--
--   Aggregating in Postgres fixes the correctness problem and collapses the
--   payload to one row per learner.
--
-- What deliberately stays in the client
--   Topics and items live in the bundled content file, not in Postgres — the
--   database only ever sees an opaque item_id. So SQL does only the arithmetic
--   that needs no content knowledge, and the client maps items to topics and
--   skills using its own bundle. Mastery WEIGHTING likewise stays in
--   scheduler.ts: this function returns the raw box histogram instead of a
--   score, so the weighting rule has exactly one home and cannot drift between
--   TypeScript and SQL.
--
-- Security
--   Both functions are SECURITY DEFINER, so they bypass RLS and the guard
--   inside each one IS the boundary. Each checks ownership explicitly, and
--   learner_item_stats additionally checks that the learner is a member of the
--   class being asked about — otherwise owning any class at all would be
--   enough to read any user's history.

-- ---------------------------------------------------------------------------
-- Per-learner summary for one class. One row per member, including members
-- who have never practised.
-- ---------------------------------------------------------------------------
create or replace function public.class_roster(p_class_id uuid)
returns table (
  user_id        uuid,
  display_name   text,
  joined_at      timestamptz,
  last_active_at timestamptz,
  seen           bigint,
  mastered       bigint,
  due            bigint,
  box_counts     bigint[],   -- boxes 1..5, so the client can apply its own
                             -- mastery weighting
  attempts       bigint,
  correct        bigint
)
language plpgsql
security definer
stable
set search_path = public
as $$
begin
  if not public.owns_class(p_class_id) then
    raise exception 'not the owner of this class' using errcode = '42501';
  end if;

  return query
  with members as (
    select m.user_id, m.joined_at
    from public.class_members m
    where m.class_id = p_class_id
  ),
  rev as (
    select
      r.user_id,
      count(*)                                  as seen,
      count(*) filter (where r.box >= 5)        as mastered,
      count(*) filter (where r.due_at <= now()) as due,
      array[
        count(*) filter (where r.box = 1),
        count(*) filter (where r.box = 2),
        count(*) filter (where r.box = 3),
        count(*) filter (where r.box = 4),
        count(*) filter (where r.box = 5)
      ]                                         as box_counts,
      max(r.updated_at)                         as last_review_at
    from public.review_state r
    join members mm on mm.user_id = r.user_id
    group by r.user_id
  ),
  att as (
    select
      a.user_id,
      count(*)                          as attempts,
      count(*) filter (where a.correct) as correct,
      max(a.created_at)                 as last_attempt_at
    from public.attempts a
    join members mm on mm.user_id = a.user_id
    group by a.user_id
  )
  select
    m.user_id,
    nullif(btrim(p.display_name), '')                      as display_name,
    m.joined_at,
    -- GREATEST ignores NULLs, so a learner with only reviews (or only
    -- attempts) still reports the timestamp they do have.
    greatest(rev.last_review_at, att.last_attempt_at)      as last_active_at,
    coalesce(rev.seen, 0)                                  as seen,
    coalesce(rev.mastered, 0)                              as mastered,
    coalesce(rev.due, 0)                                   as due,
    coalesce(rev.box_counts, array[0,0,0,0,0]::bigint[])   as box_counts,
    coalesce(att.attempts, 0)                              as attempts,
    coalesce(att.correct, 0)                               as correct
  from members m
  left join public.profiles p on p.id = m.user_id
  left join rev on rev.user_id = m.user_id
  left join att on att.user_id = m.user_id
  -- most recently active first; never-active last
  order by greatest(rev.last_review_at, att.last_attempt_at) desc nulls last,
           m.joined_at asc;
end;
$$;

-- ---------------------------------------------------------------------------
-- Per-ITEM history for ONE learner, so the teacher can see WHERE a learner is
-- struggling rather than only that they are. Bounded by the size of the
-- content bank (one row per item the learner has touched), so it cannot grow
-- without bound the way raw attempts do.
-- ---------------------------------------------------------------------------
create or replace function public.learner_item_stats(
  p_class_id uuid,
  p_user_id  uuid
)
returns table (
  item_id       text,
  box           int,
  due_at        timestamptz,
  attempts      bigint,
  wrong         bigint,
  last_wrong_at timestamptz,
  last_at       timestamptz
)
language plpgsql
security definer
stable
set search_path = public
as $$
begin
  if not public.owns_class(p_class_id) then
    raise exception 'not the owner of this class' using errcode = '42501';
  end if;
  -- Owning SOME class must not be enough to read an arbitrary user: the
  -- learner has to be in THIS one.
  if not exists (
    select 1 from public.class_members cm
    where cm.class_id = p_class_id and cm.user_id = p_user_id
  ) then
    raise exception 'not a member of this class' using errcode = '42501';
  end if;

  return query
  select
    coalesce(r.item_id, a.item_id)  as item_id,
    r.box,
    r.due_at,
    coalesce(a.attempts, 0)         as attempts,
    coalesce(a.wrong, 0)            as wrong,
    a.last_wrong_at,
    a.last_at
  from (
    select rs.item_id, rs.box, rs.due_at
    from public.review_state rs
    where rs.user_id = p_user_id
  ) r
  -- FULL OUTER so an item with attempts but no review row (or the reverse)
  -- is still reported rather than silently dropped.
  full outer join (
    select
      at2.item_id,
      count(*)                                          as attempts,
      count(*) filter (where not at2.correct)           as wrong,
      max(at2.created_at) filter (where not at2.correct) as last_wrong_at,
      max(at2.created_at)                               as last_at
    from public.attempts at2
    where at2.user_id = p_user_id
    group by at2.item_id
  ) a on a.item_id = r.item_id;
end;
$$;

revoke all on function public.class_roster(uuid)              from public;
revoke all on function public.learner_item_stats(uuid, uuid)  from public;
-- anon as well as authenticated: create_class is reachable anonymously, so an
-- anonymous owner must still be able to read their own roster.
grant execute on function public.class_roster(uuid)             to anon, authenticated;
grant execute on function public.learner_item_stats(uuid, uuid) to anon, authenticated;

-- ===========================================================================
-- 0006_avatars.sql
-- ===========================================================================

-- Kira — learner avatars
-- Paste into the Supabase SQL Editor and run, AFTER 0005_roster_rollup.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Why a column
--   Everyone already HAS a face: the client derives one from the user id, so a
--   leaderboard is never a wall of identical blanks. This column is only for
--   the face a learner has CHOSEN, and it exists so that choice follows the
--   account to a new device and is what classmates and the teacher actually
--   see — none of which is possible while it lives in local storage.
--
-- Why an emoji and not an upload
--   No file storage, no moderation queue, and no question about a child's
--   photograph sitting in a database. It also renders identically everywhere.
--
-- Why a CHECK constraint and not client-side validation
--   profiles has a self-service RLS policy from 0001, so a learner can write
--   their own row directly. Without a constraint anyone could set their
--   "avatar" to arbitrary text, and that text renders on their classmates'
--   leaderboard and on their teacher's roster. It is not an injection risk (it
--   is drawn as text, never as markup) but a classroom app should not let one
--   pupil put whatever they like in front of the others. The allow-list is the
--   boundary, and it holds no matter which write path is used.
--
--   src/app/avatar.test.ts asserts this list and the TypeScript AVATARS array
--   stay identical, so the two cannot drift apart unnoticed.

alter table public.profiles
  add column if not exists avatar text;

-- Re-runnable: drop before adding, since ADD CONSTRAINT has no IF NOT EXISTS.
alter table public.profiles
  drop constraint if exists profiles_avatar_allowed;
alter table public.profiles
  add constraint profiles_avatar_allowed check (
    avatar is null or avatar in (
      '🦊','🐼','🦉','🐬','🦁','🐢','🦋','🐝',
      '🦄','🐙','🐧','🦜','🐳','🦔','🐨','🐸'
    )
  );

-- ---------------------------------------------------------------------------
-- Setter, mirroring set_display_name. Passing null clears the choice and the
-- learner falls back to their derived face.
-- ---------------------------------------------------------------------------
create or replace function public.set_avatar(p_avatar text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clean text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;
  v_clean := nullif(btrim(coalesce(p_avatar, '')), '');
  -- the CHECK constraint rejects anything not on the list
  update public.profiles set avatar = v_clean where id = auth.uid();
  return v_clean;
end;
$$;

revoke all on function public.set_avatar(text) from public;
grant execute on function public.set_avatar(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Surface the avatar wherever a learner is shown to someone else. Both
-- functions are otherwise unchanged from 0003 / 0005 — only the extra column
-- is new, so re-running this file is the whole update.
-- ---------------------------------------------------------------------------
drop function if exists public.class_leaderboard(uuid, timestamptz);
create function public.class_leaderboard(
  p_class_id uuid,
  p_since    timestamptz
)
returns table (
  user_id      uuid,
  display_name text,
  avatar       text,
  score        bigint
)
language plpgsql
security definer
stable
set search_path = public
as $$
begin
  if not (public.is_member_of(p_class_id) or public.owns_class(p_class_id)) then
    raise exception 'not a member of this class' using errcode = '42501';
  end if;

  return query
    select
      m.user_id,
      coalesce(nullif(btrim(p.display_name), ''), 'Learner') as display_name,
      p.avatar,
      count(distinct a.item_id) as score
    from public.class_members m
    left join public.profiles p
      on p.id = m.user_id
    left join public.attempts a
      on a.user_id = m.user_id
     and a.created_at >= p_since
    where m.class_id = p_class_id
    group by m.user_id, p.display_name, p.avatar
    order by count(distinct a.item_id) desc, display_name asc;
end;
$$;

revoke all on function public.class_leaderboard(uuid, timestamptz) from public;
grant execute on function public.class_leaderboard(uuid, timestamptz)
  to anon, authenticated;

drop function if exists public.class_roster(uuid);
create function public.class_roster(p_class_id uuid)
returns table (
  user_id        uuid,
  display_name   text,
  avatar         text,
  joined_at      timestamptz,
  last_active_at timestamptz,
  seen           bigint,
  mastered       bigint,
  due            bigint,
  box_counts     bigint[],
  attempts       bigint,
  correct        bigint
)
language plpgsql
security definer
stable
set search_path = public
as $$
begin
  if not public.owns_class(p_class_id) then
    raise exception 'not the owner of this class' using errcode = '42501';
  end if;

  return query
  with members as (
    select m.user_id, m.joined_at
    from public.class_members m
    where m.class_id = p_class_id
  ),
  rev as (
    select
      r.user_id,
      count(*)                                  as seen,
      count(*) filter (where r.box >= 5)        as mastered,
      count(*) filter (where r.due_at <= now()) as due,
      array[
        count(*) filter (where r.box = 1),
        count(*) filter (where r.box = 2),
        count(*) filter (where r.box = 3),
        count(*) filter (where r.box = 4),
        count(*) filter (where r.box = 5)
      ]                                         as box_counts,
      max(r.updated_at)                         as last_review_at
    from public.review_state r
    join members mm on mm.user_id = r.user_id
    group by r.user_id
  ),
  att as (
    select
      a.user_id,
      count(*)                          as attempts,
      count(*) filter (where a.correct) as correct,
      max(a.created_at)                 as last_attempt_at
    from public.attempts a
    join members mm on mm.user_id = a.user_id
    group by a.user_id
  )
  select
    m.user_id,
    nullif(btrim(p.display_name), '')                      as display_name,
    p.avatar,
    m.joined_at,
    greatest(rev.last_review_at, att.last_attempt_at)      as last_active_at,
    coalesce(rev.seen, 0)                                  as seen,
    coalesce(rev.mastered, 0)                              as mastered,
    coalesce(rev.due, 0)                                   as due,
    coalesce(rev.box_counts, array[0,0,0,0,0]::bigint[])   as box_counts,
    coalesce(att.attempts, 0)                              as attempts,
    coalesce(att.correct, 0)                               as correct
  from members m
  left join public.profiles p on p.id = m.user_id
  left join rev on rev.user_id = m.user_id
  left join att on att.user_id = m.user_id
  order by greatest(rev.last_review_at, att.last_attempt_at) desc nulls last,
           m.joined_at asc;
end;
$$;

revoke all on function public.class_roster(uuid) from public;
grant execute on function public.class_roster(uuid) to anon, authenticated;

-- ===========================================================================
-- 0007_last_wrong_answer.sql
-- ===========================================================================

-- Kira — what the learner actually answered
-- Paste into the Supabase SQL Editor and run, AFTER 0006_avatars.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Why this exists
--   The teacher's "recently got wrong" panel can already show the question,
--   the right answer and the explanation the learner was given — all of that
--   comes out of the bundled content file. What it cannot show is the one
--   thing that turns a report into a diagnosis: WHICH wrong answer they gave.
--   "3× wrong" tells a parent to worry. "She put returns inwards on the debit
--   side, all three times" tells them what to say next.
--
--   `attempts.chosen` has held that answer since 0001; nothing has ever read
--   it back. learner_item_stats aggregates attempts away deliberately, so
--   this is a separate function rather than more columns on that one — the
--   roster asks "how is she doing", this asks "what did she put".
--
-- Shape
--   One row per item the learner has ever got wrong, carrying the MOST RECENT
--   wrong answer for it. Not every wrong attempt: the teacher is looking at a
--   miss to work out what the misconception is, and the latest one is the
--   current state of it. Bounded by the content bank the same way
--   learner_item_stats is — one row per item, not per attempt — so it cannot
--   outgrow the PostgREST row cap however long the learner practises.
--
--   `chosen` is opaque jsonb here. Its shape is per interaction type and is
--   known only to the client (grading/grade.ts), which is also the only place
--   that can render it — the database has never known what an item IS.
--
-- Security
--   SECURITY DEFINER, so it bypasses RLS and the guard inside IS the boundary.
--   It repeats BOTH checks from learner_item_stats: the caller owns the class,
--   AND the learner is a member of THAT class. Owning some class must never be
--   enough to read an arbitrary user's answers. This function is strictly more
--   sensitive than the roster ones — it returns what a learner typed, not a
--   count — so the guard is the same and the tests on it are harder.

create or replace function public.learner_last_wrong(
  p_class_id uuid,
  p_user_id  uuid
)
returns table (
  item_id    text,
  chosen     jsonb,
  wrong_at   timestamptz
)
language plpgsql
security definer
stable
set search_path = public
as $$
begin
  if not public.owns_class(p_class_id) then
    raise exception 'not the owner of this class' using errcode = '42501';
  end if;
  -- Owning SOME class must not be enough to read an arbitrary user: the
  -- learner has to be in THIS one.
  if not exists (
    select 1 from public.class_members cm
    where cm.class_id = p_class_id and cm.user_id = p_user_id
  ) then
    raise exception 'not a member of this class' using errcode = '42501';
  end if;

  return query
  -- distinct on + order by is Postgres's cheapest "latest row per group", and
  -- it uses the existing (user_id, created_at desc) index on attempts.
  select distinct on (a.item_id)
    a.item_id,
    a.chosen,
    a.created_at as wrong_at
  from public.attempts a
  where a.user_id = p_user_id
    and not a.correct
  order by a.item_id, a.created_at desc;
end;
$$;

revoke all on function public.learner_last_wrong(uuid, uuid) from public;
-- anon as well as authenticated: create_class is reachable anonymously, so an
-- anonymous owner must still be able to read their own class's detail.
grant execute on function public.learner_last_wrong(uuid, uuid) to anon, authenticated;

-- ===========================================================================
-- 0008_item_notes.sql
-- ===========================================================================

-- Kira — the teacher's better explanation, kept
-- Paste into the Supabase SQL Editor and run, AFTER 0007_last_wrong_answer.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Why this exists
--   The "recently got wrong" panel already lets a teacher read the explanation
--   the learner was given and write a better one. Until now that box was not
--   saved — it was copied into an authoring brief or it was lost, and the UI
--   said so. That was the honest thing to ship without a table, but it means
--   the one artefact in the whole loop that only a human can produce is also
--   the only one that does not survive leaving the page.
--
-- Shape
--   One row per (author, item). A better explanation for `l30-balance-off` is a
--   better explanation for it whoever missed it, so the note is keyed to the
--   ITEM, not to the learner whose miss prompted it. Keying it per learner
--   would make a teacher write the same sentence once per child.
--
--   item_id is a bare text id with no foreign key, exactly like review_state
--   and attempts: content is bundled in the client, and the database has never
--   known what an item IS. A note therefore survives the item being re-authored
--   and simply goes unread if the item is removed.
--
-- Security
--   Ordinary self-service RLS — `auth.uid() = author_id` on every path — and
--   NOT SECURITY DEFINER. This is the first thing since 0001 that needs no
--   guard inside a function, because nobody but the author ever reads a note:
--
--     * A teacher reads their own notes. That is the entire read path.
--     * Learners never see them. Free text written by one user and rendered to
--       another is precisely the surface `profiles.avatar` needed an allow-list
--       to close (0006). Author-only means there is nothing to moderate, no
--       abuse path onto a child's screen, and no reason to sanitise on read.
--     * A teacher cannot read another teacher's note, so a shared item id
--       leaks nothing between accounts.
--
--   The length bound is a CHECK and not client-side validation for the 0006
--   reason: the table is self-service under RLS, so a direct write bypasses any
--   UI. 2000 characters is a long paragraph and far short of blob storage.

create table if not exists public.item_notes (
  author_id  uuid not null references auth.users on delete cascade,
  item_id    text not null,
  note       text not null,
  updated_at timestamptz not null default now(),
  primary key (author_id, item_id)
);

-- Re-runnable: ADD CONSTRAINT has no IF NOT EXISTS.
alter table public.item_notes
  drop constraint if exists item_notes_note_length;
alter table public.item_notes
  add constraint item_notes_note_length check (
    length(note) between 1 and 2000
  );

-- An empty note is a DELETE, never a stored empty string: "I cleared this" and
-- "I wrote nothing here" must not be two different states the UI has to explain.
-- The CHECK above enforces that no matter which write path is used.

-- ---------------------------------------------------------------------------
-- updated_at is set server-side, unlike review_state's. There it is the
-- client's clock on purpose, because last-write-wins reconciliation needs the
-- writer's timestamp. A note has exactly one writer and no reconciliation, so
-- the database's own clock is both simpler and not falsifiable.
-- ---------------------------------------------------------------------------
create or replace function public.touch_item_note()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists item_notes_touch on public.item_notes;
create trigger item_notes_touch
  before insert or update on public.item_notes
  for each row execute function public.touch_item_note();

-- ---------------------------------------------------------------------------
-- RLS. This is the only boundary — Kira ships a publishable key in a public
-- bundle.
-- ---------------------------------------------------------------------------
alter table public.item_notes enable row level security;

drop policy if exists "item_notes are self-service" on public.item_notes;
create policy "item_notes are self-service" on public.item_notes
  for all
  using      (auth.uid() = author_id)
  with check (auth.uid() = author_id);

-- anon as well as authenticated: create_class is reachable anonymously, so an
-- anonymous class owner is a real teacher and must be able to keep notes.
grant select, insert, update, delete on public.item_notes to anon, authenticated;

-- ===========================================================================
-- 0009_class_insight.sql
-- ===========================================================================

-- Kira — consistency, and what the CLASS is weak at
-- Paste into the Supabase SQL Editor and run, AFTER 0008_item_notes.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Why these two
--   The roster answers "how is this learner doing" well enough. It does not
--   answer either of the two questions a teacher asks next.
--
--   1. Is she actually coming back? Mastery and accuracy both look fine on an
--      account that has not been opened in a fortnight — the number that
--      matters for spaced repetition is how many DAYS were practised, not how
--      many items. The app's own leaderboard metric was chosen for exactly
--      this reason; the teacher's roster never showed it.
--
--   2. What is the whole class weak at? Per-learner drilling does not scale
--      past one child. A teacher with a class needs the topic to reteach, not
--      six separate reading exercises.
--
-- Why class_item_stats returns ITEMS and not skills
--   Because SQL has never known what an item IS in this project — that is the
--   same rule that keeps `chosen` opaque in 0007 and keeps item_id free of a
--   foreign key in 0008. Skill tags live in seed_content.json, which is client
--   data, so this returns per-item counts and the client rolls them up through
--   the SAME weakestSkills() code the per-learner view uses. One definition of
--   "weak", not two that can drift.
--
--   It is bounded by the size of the content bank (one row per item ever
--   attempted in the class, ~253 today), not by attempts or learners, so it
--   cannot outgrow the PostgREST row cap however long the class runs.
--
-- Security
--   Both are SECURITY DEFINER, so the guard inside each IS the boundary. Both
--   are owner-only: unlike learner_item_stats there is no per-learner argument
--   to check, because the answer covers the whole class the caller owns.
--   class_activity returns one row per member and NO answer content — when a
--   learner practised, never what they put.

-- ---------------------------------------------------------------------------
-- 1. Did they come back? Seven days, one boolean each.
--
-- The timezone is the CALLER's, passed in from the browser, because this is
-- read on the teacher's screen and "today" should mean the teacher's today.
-- An unrecognised zone falls back to UTC rather than raising: a progress
-- report should not fail to load because a device reported an odd locale.
-- ---------------------------------------------------------------------------
create or replace function public.class_activity(
  p_class_id uuid,
  p_tz       text default 'UTC'
)
returns table (
  user_id uuid,
  -- 7 entries, oldest first: index 7 is today in p_tz.
  days    boolean[]
)
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_tz text;
begin
  if not public.owns_class(p_class_id) then
    raise exception 'not the owner of this class' using errcode = '42501';
  end if;

  select p_tz into v_tz
  where exists (select 1 from pg_timezone_names z where z.name = p_tz);
  v_tz := coalesce(v_tz, 'UTC');

  return query
  with members as (
    select m.user_id from public.class_members m where m.class_id = p_class_id
  ),
  -- the 7 dates being reported, in the caller's zone
  span as (
    select ((now() at time zone v_tz)::date - offs) as d
    from generate_series(6, 0, -1) as offs
  ),
  practised as (
    select distinct
      a.user_id,
      (a.created_at at time zone v_tz)::date as d
    from public.attempts a
    join members mm on mm.user_id = a.user_id
    where a.created_at >= (now() - interval '8 day')
  )
  select
    mm.user_id,
    array_agg(
      exists (
        select 1 from practised p
        where p.user_id = mm.user_id and p.d = s.d
      )
      order by s.d
    ) as days
  from members mm
  cross join span s
  group by mm.user_id;
end;
$$;

revoke all on function public.class_activity(uuid, text) from public;
-- anon too: create_class is reachable anonymously, so an anonymous owner is a
-- real teacher.
grant execute on function public.class_activity(uuid, text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. What is the class getting wrong? Per ITEM — the client turns items into
--    skills, because that mapping is content and content is client data.
-- ---------------------------------------------------------------------------
create or replace function public.class_item_stats(p_class_id uuid)
returns table (
  item_id  text,
  attempts bigint,
  wrong    bigint,
  -- how many DISTINCT learners have got this wrong. One learner failing an
  -- item six times is a conversation with that learner; four learners failing
  -- it once each is a reteach, and the totals alone cannot tell them apart.
  learners bigint
)
language plpgsql
security definer
stable
set search_path = public
as $$
begin
  if not public.owns_class(p_class_id) then
    raise exception 'not the owner of this class' using errcode = '42501';
  end if;

  return query
  select
    a.item_id,
    count(*)                                             as attempts,
    count(*) filter (where not a.correct)                 as wrong,
    count(distinct a.user_id) filter (where not a.correct) as learners
  from public.attempts a
  join public.class_members m
    on m.user_id = a.user_id
   and m.class_id = p_class_id
  group by a.item_id;
end;
$$;

revoke all on function public.class_item_stats(uuid) from public;
grant execute on function public.class_item_stats(uuid) to anon, authenticated;
